{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
  annotations:
    external-dns.alpha.kubernetes.io/target: ingress.build.resf.org
spec:
  hosts:
    {{- range .Values.istio.hosts }}
    - {{ . | quote }}
    {{- end }}
  gateways:
    {{- range .Values.istio.gateways }}
    - {{ . | quote }}
    {{- end }}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ .Release.Name }}
            port:
              number: {{ .Values.service.port }}
{{- end }}
